### ISSUE TITLE
Creating a database table dynamically, with changes audit option.

### ISSUE THREAD

**Issue by smartmeter** [dradovic/MigSharp#64]
Hello, I read on SO a recommendation about using this component :+1: I am trying to create tables dynamically from Excel

1. Can you please tell me if it will support Spatia types, SQL server 2016, and MongoDB?
2. It would be nice it I could pass it `Audit` option, means another shadow table that captures all changes with app user, db user, and timestamp.

```
var schema = new DbSchema(ConnectionString, DbPlatform.SqlServer2014);
schema.Alter(db => db.CreateTable("Customer")
     .WithAuditOption, (UserDB, UserApp, TimeStamps)  // ******* this line would be great, I can share some sql that does this if you want
     .WithPrimaryKeyColumn("Id", DbType.Int32).AsIdentity()
     .WithNotNullableColumn("First_Name", DbType.String).OfSize(50)
     .WithNotNullableColumn("Last_Name", DbType.String).OfSize(50)
     ...);
```

**Comment by dradovic** [comment]
Hi smartmeter,

This is an open-source project. Feel free to pull up PRs for whatever code you want to share :)

I can promise you that it'll be supported for long time to come since we have a couple of successful products built with it. However, there's no timeline of what features will supported at what moment in time.

As for MongoDB, I doubt it'll be ever supported as it is no-SQL with no schema. So what is there to migrate schema-wise? Or am I wrong here?
